services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-test
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./flask-app/src/static:/usr/share/nginx/static
    depends_on:
      - flask-app

  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    container_name: flask-app
    volumes:
      - ./flask-app/src/python:/app
      - ./flask-app/src/static:/app/static
    working_dir: /app
    environment:
      - STATIC_FOLDER=/app/static
    command: bash -c "pip install flask && python main.py"

